### ISSUE TITLE
Checklist para conclusão do Trabalho nr. 01 - GCS

### ISSUE THREAD

**Issue by gustavosotnas** [PedroDrim/projeto-gcs-trabalho1-grupo-06#1]
@PedroDrim @pauloXtr3m @gabrielaimeeg @gustavosotnas
##### Lembrete: Antes de fazer qualquer operação faça um `git pull` e depois de fazer uma operação faça um `git commit` e um `git push`!

- [x] **Gustavo** renomeia *tag* "1.0.0" para "linhaBase01-HierarquiaICS"

- **Gabriela, Pedro e Paulo** criam primeiros novos artefatos no formato do item **"6"**:
	- [x] **Gabriela** cria o arquivo ***Agenda de reunião 1.txt***
	- [x] **Paulo** cria o arquivo ***Iniciação 1.txt***
	- [x] **Pedro** cria o arquivo ***Planejamento 1.txt***
	- [x] **Gustavo** cria o arquivo ***Relatrorio de progresso 1.txt***

- [x] **Gabriela** cria *tag* "linhaBase02-NovosArtefatos" (item **7**)

- **Gustavo, Pedro e Gabriela** alteram os primeiros artefatos no formato do item **"8"**:
	- [x] **Gustavo** altera o arquivo ***Agenda de reunião 1.txt***
	- [x] **Pedro** altera o arquivo ***Iniciação 1.txt***
	- [x] **Gabriela** altera o arquivo ***Planejamento 1.txt***
	- [x] **Paulo** altera o arquivo ***Relatrorio de progresso 1.txt***

- [x] **Pedro** cria *tag* "linhaBase03-AlteracaoArtefatos" (item **9**)

- **TODOS** criam novos artefato segundo o item **"10"**:
	- [x] **Pedro** cria ***Ata de reunião 1.txt***
	- [x] **Paulo** cria ***Iniciação 2.txt***
	- [x] **Gustavo** cria ***Planejamento 2.txt***
	- [x] **Gabriela** cria ***Estudo de viabilidade 1.txt***
	- [x] **Pedro** cria ***Especificação de Requisitos 1.txt***
	- [x] **Paulo** cria ***Diagrama de Caso de Uso 1.txt***
	- [x] **Gustavo** cria ***Diagrama de Classe 1.txt***
	- [x] **Gabriela** cria ***Diagrama de Sequência 1.txt***
	- [x] **Pedro** cria ***Diagrama de Atividade 1.txt***

- [x] **Paulo** cria *tag* "linhaBase04-NovosArtefato" (item **11**)

- [x] **TODOS** visualizam o ***histórico de commits*** no *GitHub* / ***Log*** no *SmartGit* /`git log` (item **12**)

- **CADA UM DO GRUPO** escolhe um arquivo de texto dentre os que foram criados e:
	- [x] Altere conteúdos em linhas já existentes (o horário da criação/modificação do arquivo de texto, por exemplo)
	- [x] Inclua novas linhas (segundo o modelo especificado do item **8**)
	- [x] Abra o `git diff`/ ***Changes*** do *SmartGit* / *Meld diff tool* e visualize a diferença entre a versão atual da área de trabalho (***Working tree***) e a versão anterior (***HEAD***)
	- **Obs.:** *Não altere o mesmo arquivo que já foi alterado anteriormente!*

- [x] **Gabriela** cria nova ramificação (***branch***) "ramo2"

- [x] **TODOS** façam um ***checkout*** ("troca") para o "ramo2"

- [x] **Paulo** edita o arquivo ***Especificação de Requisitos 1.txt***, alterando linhas já existentes, incluindo novas linhas com conteúdo entre linhas existentes e novas linhas no final do documento

- [x] **Gustavo** cria o arquivo ***Especificação de Requisitos 2.txt*** no modelo especificado no item **"6"** adicionalmente, inserindo nesse documento o texto "documento criado no ramo2".

- [x] **Pedro** faz ***checkout*** para o "master" ("trunk") e cria o arquivo ***Especificação de Requisitos 2.txt*** do mesmo jeito que o *check* anterior, porém inserindo no lugar o texto "documento criado no trunk".

- [x] **Gabriela** faz ***merge*** partindo do "ramo2" para o "master", resolvendo o conflito no arquivo ***Especificação de Requisitos 1.txt***

- [x] **Gustavo** cria *tag* "linhaBase05-MergeProjeto"
